application: glslunit
version: 1
runtime: python
api_version: 1
default_expiration: "7d 5h"

handlers:
- url: /
  static_files: index.html
  upload: index.html
  
- url: /(.*)
  static_files: \1
  upload: (.*\.(html|js|css|glsl))
  
- url: /third-party
  static_dir: third-party